### ISSUE TITLE
getting configure: error: XMissingExtension not found in -lXext installing bbkeys

### ISSUE THREAD

**Issue by Nekonata-zz** [naimdjon/bbkeys#1]
Hello.  

I try to install bbkeys on Linux Debian 4.6.4-1kali1 (2016-07-21) i686 GNU/Linux

make -f Makefile.cvs all
works fine

but when I run
```
./configure && make && sudo make install
I get
checking for XMissingExtension in -lXext... no
configure: error: XMissingExtension not found in -lXext
```

I've libbt-dev

I had to install libtool like this
```
sudo apt-get install automake autoconf libtool
autoreconf -i
```

Could you help me ?

**Comment by naimdjon** [comment]
@Nekonata 
Seems like  `libxext-dev` is missing.

**Comment by tofoli** [comment]
I'm having the same problem with Ubuntu 16.10

**Comment by naimdjon** [comment]
@tofoli What does `dpkg -S libxext-dev` return? It should give you something like this:
```
root@541bfbcb74bc:~# dpkg -S libxext-dev
libxext-dev:amd64: /usr/share/doc/libxext-dev/copyright
libxext-dev:amd64: /usr/share/doc/libxext-dev/changelog.Debian.gz
libxext-dev:amd64: /usr/share/doc/libxext-dev
root@541bfbcb74bc:~# 
```
If not, you need to `apt-get update && apt-get install libxext-dev`. Try to compile bbkeys again (may need to clean up first).

**Comment by tofoli** [comment]
Many thanks @naimdjon 
Worked perfectly!!!

**Comment by naimdjon** [comment]
@Nekonata you need to install `libxext-dev`,  i.e.:
`apt-get update && apt-get install libxext-dev`
Closing the issue.
